const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
const LOGIN_UNSUCCESSFUL = "LOGIN_UNSUCCESSFUL";
const LOGOUT = "LOGOUT";
const SCHEDULE_APPOINTMENT = "SCHEDULE_APPOINTMENT";

export { LOGIN_SUCCESSFUL, LOGIN_UNSUCCESSFUL, LOGOUT, SCHEDULE_APPOINTMENT };
